### PR TITLE
Fix some minor typos

### PR DESCRIPTION
**Pull request by itsmartin**
Fix the typos suggested [here](https://oc.tc/forums/topics/554eea1fc2963589650035e7).

### CODE REVIEW

**Comment by mrapple** [comment]
Looks good

**Comment by mrapple** [comment]
Don't periods go inside parenthesis in a isolated sentence?

**Comment by stormer1267** [comment]
I am not an expert but I did some research, 
"A isolated sentence (like used in the rules)." <-- this is when they go outside, the (...) are part of the sentence just less important.
"(this does not count for ban evasion.)" <-- this is an isolated sentence, because it is a whole sentence inside parenthesis without a part being less important, instead of being a part of a sentence it now is a whole sentence inside brackets so the period has to go inside the brackets like it is already done.

Don't take my word for it though, I am not an expert. This is partly based on what I asked my Dutch teacher so it might be different in English too

**Comment by mrapple** [comment]
Yeah, that's what I meant

**Comment by itsmartin** [comment]
Yeah, from what I can see that seems to be correct. I'll undo that change.

**Comment by itsmartin** [comment]
Squashed into a single commit, this is ready to merge.

**Comment by Superjd10** [comment]
Monti @ https://octctranslations.slack.com

image

I think even this will be done in Crowdin.

**Comment by itsmartin** [comment]
Updated to new format, should be ready to merge again.

**Comment by tonybruess** [comment]
Merged: 699b1625f5962de7029cfaf372614e17be971b8a

**Pull request closed without merging**
