### PR TITLE
Added a rule regarding correct usage of /nick.

### PR DESCRIPTION
**Pull request by itsmartin**
Based on the rules given in https://oc.tc/forums/topics/5511950a5f35b9c8ef001ef0. I've left out the "greater than 4 letters" part, since I believe /nick no longer allows short names anyway.

### CODE REVIEW

**Comment by Superjd10** [comment]
I think tbjs may not apply to IF:
"any chosen nickname should be designed to confer anonymity, not attention"

If they have a star in-game that gives them enough attention, why not allow their nick to have attention too?

And as someone said on the forums like 2 days ago, do rules apply for staff? Some staff members use nicks that depending on the opinion (of the staff member or the players), gives them attention.

**Comment by itsmartin** [comment]
I don't see why the attention rule shouldn't apply to IF equally. They have /nick for the exact same reason as LPers, so that they can play anonymously.

The new rules do apply to staff, yes.

**Comment by Superjd10** [comment]
BTW, you may also update the Line 5 (last updated date) :smile: 

Would be great if this PR is merged soon, if not, it's ok.

**Comment by jedediah** [comment]
merge

**Comment by itsmartin** [comment]
Updated to new format, should be ready to merge again.

**Pull request merged**
