### PR TITLE
Section B updated Website Behavior

### PR DESCRIPTION
**Pull request by RubeVi**

### CODE REVIEW

**Comment by Superjd10** [comment]
I think I forgot how many times I have said it:

#100 - #101 - #105 - #112 - #114 - #115 - #120 

Wow, 7 times, now you are my 8th.

From #120: 

Me: "I think we are going to migrate everything website-related (including the rules) to Crowdin any time soon."

Apple: "No ETA, sorry."

Me: "So, is translating / merging pointless? I think waiting for the Crowdin project is better than merging (about 4 months or more with the rules without any translation or merge so it isn't needed IMO)"

I think I will contact the last update translators (OllieGamerZ, Gaporigo, Lordcreeper aka Equus, Arcanex), ask them for a good translation for all the spanish variations (latam and spain) and then ask @mrapple to merge it, unless he gives me some kind of perms on this repo to do it myself (ourselves if I include the mentioned translators). 

Note for Apple: I am proofreader on the Plugins's Crowdin project.

**Comment by RubeGamerV** [comment]
que?

**Comment by TiTo-418** [comment]
xDDDD

**Comment by mrapple** [comment]
@TiTo-418 if you keeping making unnecessary, incorrect, and off-topic comments on our GitHub repos I'm going to ban you from the organization.

**Comment by tonybruess** [comment]
Please translate the website on CrowdIn :) https://crowdin.com/project/ocn-website

**Pull request closed without merging**
